//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoWebBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comentario
    {
        public string correoPK { get; set; }
        public System.DateTime fechaPublicadoPK { get; set; }
        public string texto { get; set; }
        public System.DateTime fechaFK { get; set; }
        public string tituloFK { get; set; }
    
        public virtual Publicacion Publicacion { get; set; }
    }
}
